kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  wpk8s.conf.template: |
    fastcgi_cache_path /etc/nginx/cache levels=1:2 keys_zone=WORDPRESS_APP:100m max_size=10g inactive=60m use_temp_path=off;
    fastcgi_cache_key "$scheme$http_user_agent$request_method$host$request_uri";
    server {
        client_max_body_size 10M;
        listen ${NGINX_PORT};
        server_name ${NGINX_HOST};
        root ${NGINX_ROOT_DIR};
        index index.php index.html;
        add_header X-Cache $upstream_cache_status;

        location / {
            try_files $uri $uri/ /index.php?_url=$uri&$args;
            gzip on;
            gzip_comp_level 2;
            gzip_http_version 1.0;
            gzip_proxied any;
            gzip_min_length 1100;
            gzip_buffers 16 8k;
            gzip_types text/plain text/html text/css application/x-javascript text/xml application/xml application/xml+rss text/javascript;
            # Disable for IE < 6 because there are some known problems
            gzip_disable "MSIE [1-6].(?!.*SV1)";
            # Add a vary header for downstream proxies to avoid sending cached gzipped files to IE6
            gzip_vary on;
        }

        location ~ \.php {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index /index.php;
            include /etc/nginx/fastcgi_params;
            fastcgi_split_path_info       ^(.+\.php)(/.+)$;
            fastcgi_param PATH_INFO       $fastcgi_path_info;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_cache WORDPRESS_APP;
            fastcgi_cache_valid 200 301 302 60m;
            fastcgi_cache_use_stale error timeout updating invalid_header http_500 http_503;
            fastcgi_cache_min_uses 1;
            fastcgi_cache_lock on;
            add_header X-FastCGI-Cache $upstream_cache_status;
            set $skip_cache 1;
            if ($request_method = POST) {
                set $skip_cache 1;
            }
            if ($query_string != "") {
                set $skip_cache 1;
            }
            if ($request_uri ~* "/wp-admin/|/xmlrpc.php|wp-.*.php|^/feed/*|/tag/.*/feed/*|index.php|/.*sitemap.*\.(xml|xsl)") {
                set $skip_cache 1;
            }
            if ($http_cookie ~* "comment_author|wordpress_[a-f0-9]+|wp-postpass|wordpress_no_cache|wordpress_logged_in") {
                set $skip_cache 1;
            }
            fastcgi_cache_bypass $skip_cache;
            fastcgi_no_cache $skip_cache;
        }

        location ~* \.(jpg|jpeg|png|gif|ico|css|js|woff2|svg) {
            expires 1d;
            access_log off;
            add_header Cache-Control "public, max-age=31536000";
        }
    }
