apiVersion: v1 
kind: PersistentVolume
metadata:
  name: wordpress-pv
spec: 
  capacity: 
    storage: 10Gi 
  # volumeMode: Filesystem
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: <path_to_wordpress>
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
spec: 
  volumeName: wordpress-pv
  accessModes: 
    - ReadWriteOnce
  storageClassName: manual
  resources: 
    requests: 
      storage: 3Gi
