apiVersion: v1
kind: Service
metadata:
  name: wordpress-mariadb
  labels:
    app: wordpress
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
    name: mariadb
  selector:
    app: wordpress
    tier: mariadb
